Repository statamic-rad-pack/mailchimp, pull requests merged in 2023-07, with the labels that each got.

#102 Making Mailchimp radder
  .github/FUNDING.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  SECURITY.md
  composer.json
  config/mailchimp.php
  routes/cp.php
  src/Commands/GetGroups.php
  src/Commands/GetInterests.php
  src/Commands/Permissions.php
  src/Driver.php
  src/Fieldtypes/FormFields.php
  src/Fieldtypes/MailchimpAudience.php
  src/Fieldtypes/MailchimpField.php
  src/Fieldtypes/MailchimpMergeFields.php
  src/Fieldtypes/MailchimpTag.php
  src/Fieldtypes/UserFields.php
  src/Http/Controllers/ConfigController.php
  src/Http/Controllers/GetFormFieldsController.php
  src/Http/Controllers/GetMergeFieldsController.php
  src/Http/Controllers/GetTagsController.php
  src/Http/Controllers/GetUserFieldsController.php
  src/Listeners/AddFromSubmission.php
  src/Listeners/AddFromUser.php
  src/ServiceProvider.php
  src/Subscriber.php
  tests/PreventSavingStacheItemsToDisk.php
  tests/TestCase.php
  tests/Unit/ListenersTest.php
  tests/Unit/SubscriberFromSubmissionTest.php
  tests/Unit/SubscriberFromUserTest.php
Labels: major

#103 Fix license and versions
  README.md
  composer.json
Labels: fix

#106 Update config to use tabs
  resources/blueprints/config.yaml
Labels: enhancement, feature

#107 Remove Spatie\Newsletter dependency and fix marketing permissions
  composer.json
  config/mailchimp.php
  src/Commands/GetGroups.php
  src/Commands/GetInterests.php
  src/Commands/Permissions.php
  src/Driver.php
  src/Exceptions/InvalidNewsletterList.php
  src/Facades/Newsletter.php
  src/NewsletterDriver.php
  src/NewsletterList.php
  src/NewsletterListCollection.php
  src/ServiceProvider.php
  src/Subscriber.php
Labels: fix
